// const DATA = [
//   "qxfcsmh",
//   "ffsfyxbyuhqkpwatkjgudo",
//   "byc\x9dyxuafof\\\xa6uf\\axfozomj\\olh\x6a",
//   "jtqvz",
//   "uzezxa\"jgbmojtwyfbfguz",
//   "vqsremfk\x8fxiknektafj",
//   "wzntebpxnnt\"vqndz\"i\x47vvjqo\"",
//   "higvez\"k\"riewqk",
//   "dlkrbhbrlfrp\\damiauyucwhty",
//   "d\"",
//   "qlz",
//   "ku",
//   "yy\"\"uoao\"uripabop",
//   "saduyrntuswlnlkuppdro\\sicxosted",
//   "tj",
//   "zzphopswlwdhebwkxeurvizdv",
//   "xfoheirjoakrpofles\"nfu",
//   "q\xb7oh\"p\xce\"n",
//   "qeendp\"ercwgywdjeylxcv",
//   "dcmem",
//   "\"i\x13r\"l",
//   "ikso\xdcbvqnbrjduh\"uqudzki\xderwk",
//   "wfdsn",
//   "pwynglklryhtsqbno",
//   "hcoj\x63iccz\"v\"ttr",
//   "zf\x23\\hlj\\kkce\\d\\asy\"yyfestwcdxyfj",
//   "xs",
//   "m\"tvltapxdvtrxiy",
//   "bmud",
//   "k\"a",
//   "b\"oas",
//   "\"yexnjjupoqsxyqnquy\"uzfdvetqrc",
//   "vdw\xe3olxfgujaj",
//   "qomcxdnd\"\\cfoe\"",
//   "fpul",
//   "m\"avamefphkpv",
//   "vvdnb\\x\\uhnxfw\"dpubfkxfmeuhnxisd",
//   "hey\\",
//   "ldaeigghlfey",
//   "eure\"hoy\xa5iezjp\\tm",
//   "yygb\"twbj\\r\"\x10gmxuhmp\"",
//   "weirebp\x39mqonbtmfmd",
//   "ltuz\\hs\"e",
//   "ysvmpc",
//   "g\x8amjtt\"megl\"omsaihifwa",
//   "yimmm",
//   "iiyqfalh",
//   "cwknlaaf",
//   "q\x37feg\xc6s\"xx",
//   "uayrgeurgyp\\oi",
//   "xhug\"pt\"axugllbdiggzhvy",
//   "kdaarqmsjfx\xc3d",
//   "\"vkwla",
//   "d\"",
//   "tmroz\"bvfinxoe\\mum\"wmm",
//   "\"n\"bbswxne\\p\\yr\"qhwpdd",
//   "skzlkietklkqovjhvj\xfe",
//   "pbg\\pab\"bubqaf\"obzcwxwywbs\\dhtq",
//   "xxjidvqh\"lx\\wu\"ij",
//   "daef\x5fe\x5b\\kbeeb\x13qnydtboof",
//   "ogvazaqy\"j\x73",
//   "y",
//   "n\"tibetedldy\\gsamm\"nwu",
//   "wldkvgdtqulwkad",
//   "dpmxnj",
//   "twybw\"cdvf\"mjdajurokbce",
//   "ru\"\\lasij\"i",
//   "roc\\vra\\lhrm",
//   "pbkt\x60booz\"fjlkc",
//   "j\x4dytvjwrzt",
//   "\\uiwjkniumxcs",
//   "cbhm\"nexccior\"v\"j\"nazxilmfp\x47",
//   "qdxngevzrlgoq",
//   "\"lrzxftytpobsdfyrtdqpjbpuwmm\x9e",
//   "mdag\x0asnck\xc2ggj\"slb\"fjy",
//   "wyqkhjuazdtcgkcxvjkpnjdae",
//   "aixfk\xc0iom\x21vueob",
//   "dkiiakyjpkffqlluhaetires",
//   "ysspv\"lysgkvnmwbbsy",
//   "gy\"ryexcjjxdm\"xswssgtr",
//   "s",
//   "ddxv",
//   "qwt\"\x27puilb\"pslmbrsxhrz",
//   "qdg\xc9e\\qwtknlvkol\x54oqvmchn\\",
//   "lvo",
//   "b",
//   "fk\"aa\"\"yenwch\\\\on",
//   "srig\x63hpwaavs\\\x80qzk\"xa\"\xe6u\\wr",
//   "yxjxuj\"ghyhhxfj\"\xa6qvatre",
//   "yoktqxjxkzrklkoeroil",
//   "\"jfmik\"",
//   "smgseztzdwldikbqrh\"",
//   "jftahgctf\"hoqy",
//   "tcnhicr\"znpgckt\"ble",
//   "vqktnkodh\"lo\"a\\bkmdjqqnsqr",
//   "ztnirfzqq",
//   "s",
//   "xx",
//   "iqj\"y\\hqgzflwrdsusasekyrxbp\\ad",
//   "\\xzjhlaiynkioz\"\"bxepzimvgwt",
//   "s\x36rbw",
//   "mniieztwrisvdx",
//   "atyfxioy\x2b\\",
//   "irde\x85\x5cvbah\\jekw\"ia",
//   "bdmftlhkwrprmpat\"prfaocvp",
//   "w\\k",
//   "umbpausy",
//   "zfauhpsangy",
//   "p\"zqyw",
//   "wtztypyqvnnxzvlvipnq\"zu",
//   "deicgwq\\oqvajpbov\\or\"kgplwu",
//   "mbzlfgpi\\\\zqcidjpzqdzxityxa",
//   "lfkxvhma",
//   "\xf2yduqzqr\"\\fak\"p\"n",
//   "mpajacfuxotonpadvng",
//   "anb\\telzvcdu\\a\xf2flfq",
//   "lrs\"ebethwpmuuc\"\x86ygr",
//   "qmvdbhtumzc\"ci",
//   "meet",
//   "yopg\x0fdxdq\"h\\ugsu\xffmolxjv",
//   "uhy",
//   "fzgidrtzycsireghazscvmwcfmw\\t",
//   "cqohkhpgvpru",
//   "bihyigtnvmevx\"xx",
//   "xz",
//   "zofomwotzuxsjk\"q\"mc\"js\"dnmalhxd",
//   "\\ktnddux\\fqvt\"ibnjntjcbn",
//   "ia",
//   "htjadnefwetyp\xd5kbrwfycbyy",
//   "\"\\hkuxqddnao",
//   "meqqsz\x83luecpgaem",
//   "cvks\x87frvxo\"svqivqsdpgwhukmju",
//   "sgmxiai\\o\"riufxwjfigr\xdf",
//   "fgywdfecqufccpcdn",
//   "faghjoq\x28abxnpxj",
//   "zuppgzcfb\"dctvp\"elup\"zxkopx",
//   "xqs\x45xxdqcihbwghmzoa",
//   "anbnlp\\cgcvm\"hc",
//   "xf\"fgrngwzys",
//   "nrxsjduedcy\x24",
//   "\x71sxl\"gj\"sds\"ulcruguz\\t\\ssvjcwhi",
//   "jhj\"msch",
//   "qpovolktfwyiuyicbfeeju\x01",
//   "nkyxmb\"qyqultgt\"nmvzvvnxnb",
//   "ycsrkbstgzqb\"uv\\cisn",
//   "s",
//   "ueptjnn\"\"sh",
//   "lp\"z\"d\"mxtxiy",
//   "yzjtvockdnvbubqabjourf\"k\"uoxwle",
//   "\x82\"wqm\"",
//   "\xb5cwtuks\x5fpgh",
//   "wd",
//   "tbvf",
//   "ttbmzdgn",
//   "vfpiyfdejyrlbgcdtwzbnm",
//   "uc",
//   "otdcmhpjagqix",
//   "\\\xb1qso\"s",
//   "scowax",
//   "behpstjdh\xccqlgnqjyz\"eesn",
//   "r\xe1cbnjwzveoomkzlo\\kxlfouhm",
//   "jgrl",
//   "kzqs\\r",
//   "ctscb\x7fthwkdyko\"\x62pkf\"d\xe6knmhurg",
//   "tc\"kw\x3ftt",
//   "bxb\x5ccl",
//   "jyrmfbphsldwpq",
//   "jylpvysl\"\"juducjg",
//   "en\\m\"kxpq\"wpb\\\"",
//   "madouht\"bmdwvnyqvpnawiphgac\"",
//   "vuxpk\"ltucrw",
//   "aae\x60arr",
//   "ttitnne\"kilkrgssnr\xfdurzh",
//   "oalw",
//   "pc\"\"gktkdykzbdpkwigucqni\"nxiqx",
//   "dbrsaj",
//   "bgzsowyxcbrvhtvekhsh\"qgd",
//   "kudfemvk\"\"\"hkbrbil\"chkqoa",
//   "zjzgj\\ekbhyfzufy",
//   "\\acos\"fqekuxqzxbmkbnn\x1ejzwrm",
//   "elxahvudn\"txtmomotgw",
//   "\x2eoxmwdhelpr\"cgi\xf7pzvb",
//   "eapheklx",
//   "hfvma\"mietvc\"tszbbm\"czex",
//   "h\"iiockj\\\xc1et",
//   "d\"rmjjftm",
//   "qlvhdcbqtyrhlc\\",
//   "yy\"rsucjtulm\"coryri\"eqjlbmk",
//   "tv",
//   "r\"bfuht\\jjgujp\"",
//   "kukxvuauamtdosngdjlkauylttaokaj",
//   "srgost\"\"rbkcqtlccu\x65ohjptstrjkzy",
//   "yxwxl\\yjilwwxffrjjuazmzjs",
//   "dxlw\\fkstu\"hjrtiafhyuoh\"sewabne",
//   "\x88sj\"v",
//   "rfzprz\xec\"oxqclu\"krzefp\\q",
//   "cfmhdbjuhrcymgxpylllyvpni",
//   "ucrmjvmimmcq\x88\xd9\"lz",
//   "lujtt\"",
//   "gvbqoixn\"pmledpjmo\"flydnwkfxllf",
//   "dvxqlbshhmelsk\x8big\"l",
//   "mx\x54lma\x8bbguxejg",
//   "\x66jdati\xeceieo",
//   "\"iyyupixei\x54ff",
//   "xohzf\"rbxsoksxamiu",
//   "vlhthspeshzbppa\x4drhqnohjop\"\"mfjd",
//   "f\"tvxxla\"vurian\"\"idjq\x3aptm\xc3olep",
//   "gzqz",
//   "kbq\\wogye\\altvi\\hbvmodny",
//   "j\xd8",
//   "ofjozdhkblvndl",
//   "hbitoupimbawimxlxqze",
//   "ypeleimnme",
//   "xfwdrzsc\\oxqamawyizvi\\y",
//   "enoikppx\xa1ixe\"yo\"gumye",
//   "fb",
//   "vzf",
//   "zxidr",
//   "cu\x31beirsywtskq",
//   "lxpjbvqzztafwezd",
//   "\\jyxeuo\x18bv",
//   "b\"vawc\"p\\\\giern\"b",
//   "odizunx\"\"t\\yicdn\"x\"sdiz",
//   "\"\"tebrtsi",
//   "ctyzsxv\xa6pegfkwsi\"tgyltaakytccb",
//   "htxwbofchvmzbppycccliyik\xe5a",
//   "ggsslefamsklezqkrd",
//   "rcep\"fnimwvvdx\"l",
//   "zyrzlqmd\x12egvqs\\llqyie",
//   "\x07gsqyrr\\rcyhyspsvn",
//   "butg\"",
//   "gb",
//   "gywkoxf\"jsg\\wtopxvumirqxlwz",
//   "rj\"ir\"wldwveair\x2es\"dhjrdehbqnzl",
//   "ru\"elktnsbxufk\\ejufjfjlevt\\lrzd",
//   "\"widsvok",
//   "oy\"\x81nuesvw",
//   "ay",
//   "syticfac\x1cfjsivwlmy\"pumsqlqqzx",
//   "m",
//   "rjjkfh\x78cf\x2brgceg\"jmdyas\"\\xlv\xb6p",
//   "tmuvo\"\x3ffdqdovjmdmkgpstotojkv\"as",
//   "jd\\ojvynhxllfzzxvbn\"wrpphcvx",
//   "pz",
//   "\"twr",
//   "n\\hdzmxe\"mzjjeadlz",
//   "fb\"rprxuagvahjnri",
//   "rfmexmjjgh\\xrnmyvnatrvfruflaqjnd",
//   "obbbde\"co\"qr\"qpiwjgqahqm\\jjp\"",
//   "vpbq\"\"y\"czk\\b\x52ed\"lnzepobp",
//   "syzeajzfarplydipny\"y\"\xe8ad",
//   "mpyodwb",
//   "\x47rakphlqqptd",
//   "wa\"oj\"aiy",
//   "a",
//   "ropozx",
//   "q\x51nbtlwa",
//   "etukvgx\\jqxlkq",
//   "\"tp\"rah\"pg\"s\"bpdtes\\tkasdhqd",
//   "dn\"qqpkikadowssb\xcah\"dzpsf\\ect\"jdh",
//   "pxunovbbrrn\\vullyn\"bno\"\"\"myfxlp\"",
//   "qaixyazuryvkmoulhcqaotegfj\\mpzm",
//   "bvfrbicutzbjwn\\oml\"cf\"d\"ezcpv\"j",
//   "rmbrdtneudemigdhelmb",
//   "aq\\aurmbhy",
//   "wujqvzw",
//   "gf\"tssmvm\"gm\"hu\x9a\xb7yjawsa",
//   "hrhqqxow\xe2gsydtdspcfqy\"zw\\ou",
//   "ianwwf\\yko\\tdujhhqdi",
//   "xylz\"zpvpab",
//   "lwuopbeeegp",
//   "aoop\x49jhhcexdmdtun",
//   "\\\\mouqqcsgmz",
//   "tltuvwhveau\x43b\"ymxjlcgiymcynwt",
//   "gsugerumpyuhtjljbhrdyoj",
//   "lnjm\xb8wg\"ajh",
//   "zmspue\"nfttdon\\b\"eww",
//   "\"w\x67jwaq\x7ernmyvs\\rmdsuwydsd\"th",
//   "ogtgvtlmcvgllyv",
//   "z\"fqi\"rvddoehrciyl",
//   "yustxxtot\"muec\"xvfdbzunzvveq",
//   "mqslw",
//   "txqnyvzmibqgjs\xb6xy\x86nfalfyx",
//   "kzhehlmkholov",
//   "plpmywcnirrjutjguosh\\",
//   "pydbnqofv\"dn\\m",
//   "aegqof",
//   "eambmxt\\dxagoogl\\zapfwwlmk",
//   "afbmqitxxqhddlozuxcpjxgh",
//   "vgts",
//   "bfdpqtoxzzhmzcilehnflna",
//   "s\"idpz",
//   "\xcfhgly\"nlmztwybx\"ecezmsxaqw",
//   "aackfgndqcqiy",
//   "\x22unqdlsrvgzfaohoffgxzfpir\"s",
//   "abh\"ydv\"kbpdhrerl",
//   "bdzpg",
//   "ekwgkywtmzp",
//   "wtoodejqmrrgslhvnk\"pi\"ldnogpth",
//   "njro\x68qgbx\xe4af\"\\suan",
// ];

// Z = \


const DATA2 = [
  '"qxfcsmh"',
  '"ffsfyxbyuhqkpwatkjgudo"',
  '"bycZx9dyxuafofZZZxa6ufZZaxfozomjZZolhZx6a"',
  '"jtqvz"',
  '"uzezxaZ"jgbmojtwyfbfguz"',
  '"vqsremfkZx8fxiknektafj"',
  '"wzntebpxnntZ"vqndzZ"iZx47vvjqoZ""',
  '"higvezZ"kZ"riewqk"',
  '"dlkrbhbrlfrpZZdamiauyucwhty"',
  '"dZ""',
  '"qlz"',
  '"ku"',
  '"yyZ"Z"uoaoZ"uripabop"',
  '"saduyrntuswlnlkuppdroZZsicxosted"',
  '"tj"',
  '"zzphopswlwdhebwkxeurvizdv"',
  '"xfoheirjoakrpoflesZ"nfu"',
  '"qZxb7ohZ"pZxceZ"n"',
  '"qeendpZ"ercwgywdjeylxcv"',
  '"dcmem"',
  '"Z"iZx13rZ"l"',
  '"iksoZxdcbvqnbrjduhZ"uqudzkiZxderwk"',
  '"wfdsn"',
  '"pwynglklryhtsqbno"',
  '"hcojZx63icczZ"vZ"ttr"',
  '"zfZx23ZZhljZZkkceZZdZZasyZ"yyfestwcdxyfj"',
  '"xs"',
  '"mZ"tvltapxdvtrxiy"',
  '"bmud"',
  '"kZ"a"',
  '"bZ"oas"',
  '"Z"yexnjjupoqsxyqnquyZ"uzfdvetqrc"',
  '"vdwZxe3olxfgujaj"',
  '"qomcxdndZ"ZZcfoeZ""',
  '"fpul"',
  '"mZ"avamefphkpv"',
  '"vvdnbZZxZZuhnxfwZ"dpubfkxfmeuhnxisd"',
  '"heyZZ"',
  '"ldaeigghlfey"',
  '"eureZ"hoyZxa5iezjpZZtm"',
  '"yygbZ"twbjZZrZ"Zx10gmxuhmpZ""',
  '"weirebpZx39mqonbtmfmd"',
  '"ltuzZZhsZ"e"',
  '"ysvmpc"',
  '"gZx8amjttZ"meglZ"omsaihifwa"',
  '"yimmm"',
  '"iiyqfalh"',
  '"cwknlaaf"',
  '"qZx37fegZxc6sZ"xx"',
  '"uayrgeurgypZZoi"',
  '"xhugZ"ptZ"axugllbdiggzhvy"',
  '"kdaarqmsjfxZxc3d"',
  '"Z"vkwla"',
  '"dZ""',
  '"tmrozZ"bvfinxoeZZmumZ"wmm"',
  '"Z"nZ"bbswxneZZpZZyrZ"qhwpdd"',
  '"skzlkietklkqovjhvjZxfe"',
  '"pbgZZpabZ"bubqafZ"obzcwxwywbsZZdhtq"',
  '"xxjidvqhZ"lxZZwuZ"ij"',
  '"daefZx5feZx5bZZkbeebZx13qnydtboof"',
  '"ogvazaqyZ"jZx73"',
  '"y"',
  '"nZ"tibetedldyZZgsammZ"nwu"',
  '"wldkvgdtqulwkad"',
  '"dpmxnj"',
  '"twybwZ"cdvfZ"mjdajurokbce"',
  '"ruZ"ZZlasijZ"i"',
  '"rocZZvraZZlhrm"',
  '"pbktZx60boozZ"fjlkc"',
  '"jZx4dytvjwrzt"',
  '"ZZuiwjkniumxcs"',
  '"cbhmZ"nexcciorZ"vZ"jZ"nazxilmfpZx47"',
  '"qdxngevzrlgoq"',
  '"Z"lrzxftytpobsdfyrtdqpjbpuwmmZx9e"',
  '"mdagZx0asnckZxc2ggjZ"slbZ"fjy"',
  '"wyqkhjuazdtcgkcxvjkpnjdae"',
  '"aixfkZxc0iomZx21vueob"',
  '"dkiiakyjpkffqlluhaetires"',
  '"ysspvZ"lysgkvnmwbbsy"',
  '"gyZ"ryexcjjxdmZ"xswssgtr"',
  '"s"',
  '"ddxv"',
  '"qwtZ"Zx27puilbZ"pslmbrsxhrz"',
  '"qdgZxc9eZZqwtknlvkolZx54oqvmchnZZ"',
  '"lvo"',
  '"b"',
  '"fkZ"aaZ"Z"yenwchZZZZon"',
  '"srigZx63hpwaavsZZZx80qzkZ"xaZ"Zxe6uZZwr"',
  '"yxjxujZ"ghyhhxfjZ"Zxa6qvatre"',
  '"yoktqxjxkzrklkoeroil"',
  '"Z"jfmikZ""',
  '"smgseztzdwldikbqrhZ""',
  '"jftahgctfZ"hoqy"',
  '"tcnhicrZ"znpgcktZ"ble"',
  '"vqktnkodhZ"loZ"aZZbkmdjqqnsqr"',
  '"ztnirfzqq"',
  '"s"',
  '"xx"',
  '"iqjZ"yZZhqgzflwrdsusasekyrxbpZZad"',
  '"ZZxzjhlaiynkiozZ"Z"bxepzimvgwt"',
  '"sZx36rbw"',
  '"mniieztwrisvdx"',
  '"atyfxioyZx2bZZ"',
  '"irdeZx85Zx5cvbahZZjekwZ"ia"',
  '"bdmftlhkwrprmpatZ"prfaocvp"',
  '"wZZk"',
  '"umbpausy"',
  '"zfauhpsangy"',
  '"pZ"zqyw"',
  '"wtztypyqvnnxzvlvipnqZ"zu"',
  '"deicgwqZZoqvajpbovZZorZ"kgplwu"',
  '"mbzlfgpiZZZZzqcidjpzqdzxityxa"',
  '"lfkxvhma"',
  '"Zxf2yduqzqrZ"ZZfakZ"pZ"n"',
  '"mpajacfuxotonpadvng"',
  '"anbZZtelzvcduZZaZxf2flfq"',
  '"lrsZ"ebethwpmuucZ"Zx86ygr"',
  '"qmvdbhtumzcZ"ci"',
  '"meet"',
  '"yopgZx0fdxdqZ"hZZugsuZxffmolxjv"',
  '"uhy"',
  '"fzgidrtzycsireghazscvmwcfmwZZt"',
  '"cqohkhpgvpru"',
  '"bihyigtnvmevxZ"xx"',
  '"xz"',
  '"zofomwotzuxsjkZ"qZ"mcZ"jsZ"dnmalhxd"',
  '"ZZktndduxZZfqvtZ"ibnjntjcbn"',
  '"ia"',
  '"htjadnefwetypZxd5kbrwfycbyy"',
  '"Z"ZZhkuxqddnao"',
  '"meqqszZx83luecpgaem"',
  '"cvksZx87frvxoZ"svqivqsdpgwhukmju"',
  '"sgmxiaiZZoZ"riufxwjfigrZxdf"',
  '"fgywdfecqufccpcdn"',
  '"faghjoqZx28abxnpxj"',
  '"zuppgzcfbZ"dctvpZ"elupZ"zxkopx"',
  '"xqsZx45xxdqcihbwghmzoa"',
  '"anbnlpZZcgcvmZ"hc"',
  '"xfZ"fgrngwzys"',
  '"nrxsjduedcyZx24"',
  '"Zx71sxlZ"gjZ"sdsZ"ulcruguzZZtZZssvjcwhi"',
  '"jhjZ"msch"',
  '"qpovolktfwyiuyicbfeejuZx01"',
  '"nkyxmbZ"qyqultgtZ"nmvzvvnxnb"',
  '"ycsrkbstgzqbZ"uvZZcisn"',
  '"s"',
  '"ueptjnnZ"Z"sh"',
  '"lpZ"zZ"dZ"mxtxiy"',
  '"yzjtvockdnvbubqabjourfZ"kZ"uoxwle"',
  '"Zx82Z"wqmZ""',
  '"Zxb5cwtuksZx5fpgh"',
  '"wd"',
  '"tbvf"',
  '"ttbmzdgn"',
  '"vfpiyfdejyrlbgcdtwzbnm"',
  '"uc"',
  '"otdcmhpjagqix"',
  '"ZZZxb1qsoZ"s"',
  '"scowax"',
  '"behpstjdhZxccqlgnqjyzZ"eesn"',
  '"rZxe1cbnjwzveoomkzloZZkxlfouhm"',
  '"jgrl"',
  '"kzqsZZr"',
  '"ctscbZx7fthwkdykoZ"Zx62pkfZ"dZxe6knmhurg"',
  '"tcZ"kwZx3ftt"',
  '"bxbZx5ccl"',
  '"jyrmfbphsldwpq"',
  '"jylpvyslZ"Z"juducjg"',
  '"enZZmZ"kxpqZ"wpbZZZ""',
  '"madouhtZ"bmdwvnyqvpnawiphgacZ""',
  '"vuxpkZ"ltucrw"',
  '"aaeZx60arr"',
  '"ttitnneZ"kilkrgssnrZxfdurzh"',
  '"oalw"',
  '"pcZ"Z"gktkdykzbdpkwigucqniZ"nxiqx"',
  '"dbrsaj"',
  '"bgzsowyxcbrvhtvekhshZ"qgd"',
  '"kudfemvkZ"Z"Z"hkbrbilZ"chkqoa"',
  '"zjzgjZZekbhyfzufy"',
  '"ZZacosZ"fqekuxqzxbmkbnnZx1ejzwrm"',
  '"elxahvudnZ"txtmomotgw"',
  '"Zx2eoxmwdhelprZ"cgiZxf7pzvb"',
  '"eapheklx"',
  '"hfvmaZ"mietvcZ"tszbbmZ"czex"',
  '"hZ"iiockjZZZxc1et"',
  '"dZ"rmjjftm"',
  '"qlvhdcbqtyrhlcZZ"',
  '"yyZ"rsucjtulmZ"coryriZ"eqjlbmk"',
  '"tv"',
  '"rZ"bfuhtZZjjgujpZ""',
  '"kukxvuauamtdosngdjlkauylttaokaj"',
  '"srgostZ"Z"rbkcqtlccuZx65ohjptstrjkzy"',
  '"yxwxlZZyjilwwxffrjjuazmzjs"',
  '"dxlwZZfkstuZ"hjrtiafhyuohZ"sewabne"',
  '"Zx88sjZ"v"',
  '"rfzprzZxecZ"oxqcluZ"krzefpZZq"',
  '"cfmhdbjuhrcymgxpylllyvpni"',
  '"ucrmjvmimmcqZx88Zxd9Z"lz"',
  '"lujttZ""',
  '"gvbqoixnZ"pmledpjmoZ"flydnwkfxllf"',
  '"dvxqlbshhmelskZx8bigZ"l"',
  '"mxZx54lmaZx8bbguxejg"',
  '"Zx66jdatiZxeceieo"',
  '"Z"iyyupixeiZx54ff"',
  '"xohzfZ"rbxsoksxamiu"',
  '"vlhthspeshzbppaZx4drhqnohjopZ"Z"mfjd"',
  '"fZ"tvxxlaZ"vurianZ"Z"idjqZx3aptmZxc3olep"',
  '"gzqz"',
  '"kbqZZwogyeZZaltviZZhbvmodny"',
  '"jZxd8"',
  '"ofjozdhkblvndl"',
  '"hbitoupimbawimxlxqze"',
  '"ypeleimnme"',
  '"xfwdrzscZZoxqamawyizviZZy"',
  '"enoikppxZxa1ixeZ"yoZ"gumye"',
  '"fb"',
  '"vzf"',
  '"zxidr"',
  '"cuZx31beirsywtskq"',
  '"lxpjbvqzztafwezd"',
  '"ZZjyxeuoZx18bv"',
  '"bZ"vawcZ"pZZZZgiernZ"b"',
  '"odizunxZ"Z"tZZyicdnZ"xZ"sdiz"',
  '"Z"Z"tebrtsi"',
  '"ctyzsxvZxa6pegfkwsiZ"tgyltaakytccb"',
  '"htxwbofchvmzbppycccliyikZxe5a"',
  '"ggsslefamsklezqkrd"',
  '"rcepZ"fnimwvvdxZ"l"',
  '"zyrzlqmdZx12egvqsZZllqyie"',
  '"Zx07gsqyrrZZrcyhyspsvn"',
  '"butgZ""',
  '"gb"',
  '"gywkoxfZ"jsgZZwtopxvumirqxlwz"',
  '"rjZ"irZ"wldwveairZx2esZ"dhjrdehbqnzl"',
  '"ruZ"elktnsbxufkZZejufjfjlevtZZlrzd"',
  '"Z"widsvok"',
  '"oyZ"Zx81nuesvw"',
  '"ay"',
  '"syticfacZx1cfjsivwlmyZ"pumsqlqqzx"',
  '"m"',
  '"rjjkfhZx78cfZx2brgcegZ"jmdyasZ"ZZxlvZxb6p"',
  '"tmuvoZ"Zx3ffdqdovjmdmkgpstotojkvZ"as"',
  '"jdZZojvynhxllfzzxvbnZ"wrpphcvx"',
  '"pz"',
  '"Z"twr"',
  '"nZZhdzmxeZ"mzjjeadlz"',
  '"fbZ"rprxuagvahjnri"',
  '"rfmexmjjghZZxrnmyvnatrvfruflaqjnd"',
  '"obbbdeZ"coZ"qrZ"qpiwjgqahqmZZjjpZ""',
  '"vpbqZ"Z"yZ"czkZZbZx52edZ"lnzepobp"',
  '"syzeajzfarplydipnyZ"yZ"Zxe8ad"',
  '"mpyodwb"',
  '"Zx47rakphlqqptd"',
  '"waZ"ojZ"aiy"',
  '"a"',
  '"ropozx"',
  '"qZx51nbtlwa"',
  '"etukvgxZZjqxlkq"',
  '"Z"tpZ"rahZ"pgZ"sZ"bpdtesZZtkasdhqd"',
  '"dnZ"qqpkikadowssbZxcahZ"dzpsfZZectZ"jdh"',
  '"pxunovbbrrnZZvullynZ"bnoZ"Z"Z"myfxlpZ""',
  '"qaixyazuryvkmoulhcqaotegfjZZmpzm"',
  '"bvfrbicutzbjwnZZomlZ"cfZ"dZ"ezcpvZ"j"',
  '"rmbrdtneudemigdhelmb"',
  '"aqZZaurmbhy"',
  '"wujqvzw"',
  '"gfZ"tssmvmZ"gmZ"huZx9aZxb7yjawsa"',
  '"hrhqqxowZxe2gsydtdspcfqyZ"zwZZou"',
  '"ianwwfZZykoZZtdujhhqdi"',
  '"xylzZ"zpvpab"',
  '"lwuopbeeegp"',
  '"aoopZx49jhhcexdmdtun"',
  '"ZZZZmouqqcsgmz"',
  '"tltuvwhveauZx43bZ"ymxjlcgiymcynwt"',
  '"gsugerumpyuhtjljbhrdyoj"',
  '"lnjmZxb8wgZ"ajh"',
  '"zmspueZ"nfttdonZZbZ"eww"',
  '"Z"wZx67jwaqZx7ernmyvsZZrmdsuwydsdZ"th"',
  '"ogtgvtlmcvgllyv"',
  '"zZ"fqiZ"rvddoehrciyl"',
  '"yustxxtotZ"muecZ"xvfdbzunzvveq"',
  '"mqslw"',
  '"txqnyvzmibqgjsZxb6xyZx86nfalfyx"',
  '"kzhehlmkholov"',
  '"plpmywcnirrjutjguoshZZ"',
  '"pydbnqofvZ"dnZZm"',
  '"aegqof"',
  '"eambmxtZZdxagooglZZzapfwwlmk"',
  '"afbmqitxxqhddlozuxcpjxgh"',
  '"vgts"',
  '"bfdpqtoxzzhmzcilehnflna"',
  '"sZ"idpz"',
  '"ZxcfhglyZ"nlmztwybxZ"ecezmsxaqw"',
  '"aackfgndqcqiy"',
  '"Zx22unqdlsrvgzfaohoffgxzfpirZ"s"',
  '"abhZ"ydvZ"kbpdhrerl"',
  '"bdzpg"',
  '"ekwgkywtmzp"',
  '"wtoodejqmrrgslhvnkZ"piZ"ldnogpth"',
  '"njroZx68qgbxZxe4afZ"ZZsuan"',
];

const literalChars = line => line.length;;
const memoryChars = line => {
  line = line.replace(/Z\"/g, '"');
  line = line.replace(/ZZ/g, '\\');
  line = line.replace(/Zx../g, '_');
  return line.length - 2;
};



// const CODE_LEN = DATA2.map(line => line.length);
// const MEMORY_LEN = DATA.map(line => line.length + 2);
//
const sum = (list) => list.reduce((prev, cur) => prev + cur, 0);

// const str = '"aaaZ"aaa"';
// console.log(literalChars(str));
// console.log(memoryChars(str));

const diffs = DATA2.map(line => literalChars(line) - memoryChars(line));
// console.log(sum(diffs));


//////


const encodedChars = line => {
  const newLine = line
  .replace(/Z/g, '|Z')
  .replace(/\"/g, '|"');
    // .replace(/Z\"/g, '|Z"')
    // .replace(/\"/g, '|"')
    // .replace(/Zx/g, '|Zx');
  return newLine.length + 2;
};

const numEncodings = line => {

};

const DATA3 = ['""', '"abc"', '"aaaZ"aaa"', '"Zx27"' ]
// const diffs2 = DATA3.map(line => [literalChars(line), encodedChars(line), encodedChars(line) - literalChars(line)]);
// console.log(diffs2);
const diffs2 = DATA2.map(line => encodedChars(line) - literalChars(line));

console.log(sum(diffs2));
